### ISSUE TITLE
Locations missing on map

### ISSUE THREAD

**Issue by ronshilo** [oferb/israelcoronamap#117]
![3CC4FB4D-6DAD-408A-8ACD-6F34BEDCC3D4](https://user-images.githubusercontent.com/16280233/77687289-d363aa80-6fa6-11ea-9cd5-e29c563dfc89.jpeg)
![D3558302-AB08-4037-A6FC-EC343E308163](https://user-images.githubusercontent.com/16280233/77687297-d78fc800-6fa6-11ea-84ac-3ea53482084e.jpeg)

Location data from Department of Health website

https://www.gov.il/he/departments/news/telaviv-corona

**Comment by oferb** [comment]
Hi,
We get our data from the Ministry of Health, so they're the address for this issue.
Thanks!
