### ISSUE TITLE
Improve SEO (currently scoring 90)

### ISSUE THREAD

**Issue by oferb** [oferb/israelcoronamap#21]
Use Google Lighthouse report to see what to fix:
https://developers.google.com/web/tools/lighthouse

![image](https://user-images.githubusercontent.com/5137671/76654798-7f9f9d00-6574-11ea-884a-7eeb312a8517.png)

Here's the report:
![image](https://user-images.githubusercontent.com/5137671/76654782-79112580-6574-11ea-95be-3a0a7147ec60.png)

These links can also help:
https://support.google.com/webmasters/answer/9128669
https://support.google.com/webmasters/answer/79812

**Comment by eilatc** [comment]
![image](https://user-images.githubusercontent.com/19334770/77226709-0e1eaa80-6b83-11ea-9cb9-e48d98aed1b5.png)

we fix it, we can close.
