### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by oferb** [oferb/israelcoronamap#58]
A page with general statistics.
Need to think about design, and which statistics we want to show

**Comment by zomer-g** [comment]
i can do it really fast in data-studio

i started to collect data for that (such as daily summary)
https://docs.google.com/spreadsheets/d/18JZNGQBqh6tq2FbeYv72pIeJWGyk2C6K18qFJs4FCYY/edit#gid=1326551472


just tell me colors and king of data/tables/graphs you want and resolution for embed and i will do it.

**Comment by oferb** [comment]
Done
