### ISSUE TITLE
MyCorona

### ISSUE THREAD

**Issue by oferb** [oferb/israelcoronamap#59]
Allow users to *locally* process Google Timeline data (KML/JSON) from their account to see if there's an overlap with a location + time on the map.

Can take a look at:
https://github.com/yjlou/2019-nCov

Website for the code:
http://pandemic.events/?hl=he

**Comment by aridot** [comment]
I think the killer app would be using a chrome extension - Opened https://github.com/oferb/israelcoronamap/issues/67

**Comment by mmaorc** [comment]
I'm doing that as well, although in python currently. If you need references or want to cooperate I'll be happy to.
https://github.com/mmaorc/covid19-encounters

**Comment by oferb** [comment]
Update from @aridot - apparently Chrome extensions as are Android apps that deal with Coronavirus are not approved, to avoid fake news.
