### ISSUE TITLE
Marker de-clutter bug - important for transmission awareness 

### ISSUE THREAD

**Issue by OmKoren** [oferb/israelcoronamap#64]
I tried to find transmission events in israelcoronamap.co.il.
I looked at "The Red Pirate", Or Yehuda ("lat": 32.0228009,"lon": 34.861666).
According to the data - there were two different people there (pat_num: 10 and pat_num: 13).
The map only shows the details of patience # 13.
I think this is a de-clutter bug - both markers are probably visualized on top of one another, and only the top one is selectable.
When i looked at the data itself, the json at https://israelcoronamap.co.il/data/data.json - both were present.
Attaching some print screens.

![image](https://user-images.githubusercontent.com/17431695/76679823-3c811080-65ec-11ea-9e93-67f2501b31ab.png)

![image](https://user-images.githubusercontent.com/17431695/76679842-6d614580-65ec-11ea-8eae-896d9287a254.png)

**Comment by ShayMalchi** [comment]
Fixed in #68. Thanks

**Comment by OmKoren** [comment]
Awesome, thanks!
