### ISSUE TITLE
CoronaTimelines

### ISSUE THREAD

**Issue by aridot** [oferb/israelcoronamap#67]
1. Chrome extension
- Utilizing the Google (And Apple in the future) Location Timeline with a Chrome Extension compared to the confirmed COVID-19 Timelines.
- Show any matched encounters (time/geo) with a confirmed case and allow seeing the description + dismissing non-relevant matched.
- Keep track of last usage of the extension, upon re-entry, compare since the last usage.
- Keep track of logged-in user, allow different users using the same browsers.

**Comment by oferb** [comment]
Chrome extensions that deal with Coronavirus are not approved (per @aridot).

**Comment by aridot** [comment]
They actually approved my first version, but not my more recent (fixed API to the data points and error handling), so it's still unusable. Plus, they emailed me saying that DUE to the COVID-19 they are experiencing a lag in reviewing and approving. The irony.
https://github.com/aridot/coronaext
@oferb
